name: Update README

on:
  push:
    paths:
      - 'data/*.json' # Trigger the action when JSON files in 'your-folder' are changed
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install pyyaml

    - name: Update README
      run: python .github/scripts/update_readme.py

    # Commit changes
    - name: Commit and push if it changed
      run: |
        git diff
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -A
        git diff --exit-code || git commit -m "Automatically update README"
        git push origin HEAD:master  # Push changes to the master branch
