name: Update README

on:
  push:
    paths:
      - 'data/*.json' # Trigger the action when JSON files in 'your-folder' are changed
  schedule:
    - cron: '0 0 * * *' # Or you can run it every day at midnight

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install pyyaml

    - name: Update README
      run: python .github/scripts/update_readme.py
